In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [7]:
x = np.array([[1,2,3,4,5]])

In [12]:
x.T.dot(x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [13]:
x*x

array([[ 1,  4,  9, 16, 25]])

In [14]:
x.sum(axis=0)

array([1, 2, 3, 4, 5])

In [15]:
x.sum(axis=1)

array([15])

array([[4, 5, 6],
       [7, 8, 9]])